// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBffANe5Co6Et4q-bskuWP0e6AeFvcH6dQ',
    appId: '1:812181551915:android:f60ea42312823383d8e36e',
    messagingSenderId: '812181551915',
    projectId: 'flutterfirebasequiz230129',
    storageBucket: 'flutterfirebasequiz230129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6QWE1ug6oAWb5LpKxv5Z4SqOvBYOUOp0',
    appId: '1:812181551915:ios:272b5ce432e59db0d8e36e',
    messagingSenderId: '812181551915',
    projectId: 'flutterfirebasequiz230129',
    storageBucket: 'flutterfirebasequiz230129.appspot.com',
    iosClientId: '812181551915-97mmfe85d8khrsddgm3ruc2l44iotvu8.apps.googleusercontent.com',
    iosBundleId: 'com.flutterkage2k.flutterfirebasequiz230129',
  );
}
